[package]
name = "todo_app"
version = "0.1.0"
authors = ["hongthaipham <hongthaipro@gmail.com>", "joel george <idiaghegeorge9@gmail.com>"]
edition = "2024"

[dependencies]
ink = { version = "6.0.0-alpha", default-features = false }
ink_primitives = "5.1.1"
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }

[dev-dependencies]
ink_e2e = { version = "6.0.0-alpha" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = ["ink/std"]
ink-as-dependency = []
e2e-tests = []
